name: CI for library-rent

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REPOSITORY: vkdahdk/library-rent

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REPOSITORY }}:latest
            ${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}

      - name: Update image tag in infra repo
        env:
          GITHUB_TOKEN: ${{ secrets.INFRA_REPO_PAT }}
        run: |
          git clone https://github.com/vkdahdk/library-infra.git
          cd infra
          git config user.name "GitHub Actions Bot"
          git config user.email "rent@users.noreply.github.com"
          sed -i 's|image: .*|image: ${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}|' applications/library-rent/deployment.yaml
          git add applications/library-rent/deployment.yaml
          git commit -m "Update library-rent image to ${{ github.sha }}"
          git push